/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swing_project;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class start extends javax.swing.JFrame  implements Runnable{
String uname,dpt;
String ans;
int minute,second=59;
 int count=1;
 String dbcount;
 String q[]=new String[1000];
 String o1[]=new String[100];
 String o2[]=new String[100];
 String o3[]=new String[100];
 String o4[]=new String[100];
 String an[]=new String[100];
 int i=1;
 int cor=0;
 int w=0;
 int mark=0;
 String right;
 db db= db=new db();
 ResultSet rs;
   PreparedStatement ps;
    Connection con=db.getcon();
    /**
     * Creates new form start
     */
    public start() {
        initComponents();
        buttonGroup1.add(r1);
        buttonGroup1.add(r2);
        buttonGroup1.add(r3);
        buttonGroup1.add(r4);
    }
public start(String user,String dept,String dbcount1) {
     uname=user;
     dpt=dept;
     dbcount=dbcount1;
     minute=Integer.parseInt(dbcount1)-1;
        initComponents();
        buttonGroup1.add(r1);
        buttonGroup1.add(r2);
        buttonGroup1.add(r3);
        buttonGroup1.add(r4);
        r1.setSelected(false);
        r2.setSelected(false);
        r3.setSelected(false);
        r4.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lq = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        bn = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        rbtn = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lq.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        bn.setText("next");
        bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnActionPerformed(evt);
            }
        });

        btnsave.setText("Save and Submit");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        rbtn.setText("Result");
        rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnActionPerformed(evt);
            }
        });

        lbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lq, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r2)
                            .addComponent(r1)
                            .addComponent(r3)
                            .addComponent(r4))))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addGap(29, 29, 29)
                        .addComponent(bn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(r1)
                .addGap(27, 27, 27)
                .addComponent(r2)
                .addGap(35, 35, 35)
                .addComponent(r3)
                .addGap(32, 32, 32)
                .addComponent(r4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bn)
                    .addComponent(btnsave)
                    .addComponent(rbtn))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         getContentPane().setBackground(Color.PINK); 
          try{
              Thread th=new Thread(this,"thread");
              th.start();
        // db=new db();
       // con=db.getcon();
      // int i=0;
         rbtn.setVisible(false);
         ps=con.prepareStatement("select * from tbl_treg t,tbl_question q where t.tid=q.tid and t.tsubject=? order by rand()");
        ps.setString(1,dpt);
        rs= ps.executeQuery();
       
      if(rs.first())
       {
       // if(i<Integer.parseInt(dbcount)){ 
       lq.setText("Q"+i+rs.getString("question"));
        r1.setText(rs.getString("option1"));
        r2.setText(rs.getString("option2"));
        r3.setText(rs.getString("option3"));
        r4.setText(rs.getString("option4"));
     ans=rs.getString("answer");
     // i ++; 
       // }
     /*bn.addActionListener(new ActionListener(){

           @Override
           public void actionPerformed(ActionEvent e) {
               i++;
               
               throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           }
     });*/
       }
       //JOptionPane.showMessageDialog(null,count);
       
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_formWindowActivated

    private void bnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnActionPerformed
        // TODO add your handling code here:
        /* r1.setSelected(false);
        r2.setSelected(false);
        r3.setSelected(false);
        r4.setSelected(false);*/
       // r1.clearSelection();
        buttonGroup1.clearSelection();
        
         //  count++;
     /* */
      /*  if(r1.isSelected()){
        right=r1.getText();
        }
        else  if(r2.isSelected()){
        right=r2.getText();
        } 
        else  if(r3.isSelected()){
        right=r3.getText();
        } 
        else  if(r4.isSelected()){
        right=r4.getText();
        } 
        JOptionPane.showMessageDialog(null,right);
        JOptionPane.showMessageDialog(null,ans);*/
       // if(right.equals(ans))
     //   click();
        i++;
       
        try{
     if(rs.next())
     {
        /* r1.setSelected(false);
        r2.setSelected(false);
        r3.setSelected(false);
        r4.setSelected(false);*/
     // rs.next();
     lq.setText("Q"+i+rs.getString("question"));
        r1.setText(rs.getString("option1"));
        r2.setText(rs.getString("option2"));
        r3.setText(rs.getString("option3"));
        r4.setText(rs.getString("option4"));
     ans=rs.getString("answer");    
     }
 else  if(rs.last())
     {
         bn.setVisible(false); 
         btnsave.setVisible(false);
          rbtn.setVisible(true);
     }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_bnActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
         if(r1.isSelected()){
        right=r1.getText();
        }
        else  if(r2.isSelected()){
        right=r2.getText();
        } 
        else  if(r3.isSelected()){
        right=r3.getText();
        } 
        else  if(r4.isSelected()){
        right=r4.getText();
        } 
         // JOptionPane.showMessageDialog(null,right);
       // JOptionPane.showMessageDialog(null,ans);
         if(right.equals(ans))
         {
      cor ++;
      mark=mark+1;
         }
         else
         {
             w++;
         }
         r1.setSelected(false);
          r2.setSelected(false);
           r3.setSelected(false);
            r4.setSelected(false);
         
       //  JOptionPane.showMessageDialog(null,"saved");
    }//GEN-LAST:event_btnsaveActionPerformed

    private void rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnActionPerformed
    try {
        // TODO add your handling code here:
       
        con=db.getcon();
        String id = null;
        ps=con.prepareStatement("select sid from tbl_sreg where susername=?");
        ps.setString(1,uname);
        rs=ps.executeQuery();
        while(rs.next()){
        id=rs.getString("sid");
        }
        PreparedStatement ps1=con.prepareStatement("insert into tbl_ans(correct,wrong,mark,totalq,sid)values(?,?,?,?,?)");
        ps1.setString(1,String.valueOf(cor));
        ps1.setString(2,String.valueOf(w));
        ps1.setString(3,String.valueOf(mark));
        ps1.setString(4,dbcount);
        ps1.setString(5,id);
     ps1.executeUpdate();
    /* if(x>0)
     {
        // JOptionPane.showMessageDialog(null,"inserted");
     }*/
      // if(second==00 && minute==00) {
        new result(cor,w,mark,dbcount,uname,dpt).setVisible(true);
     /*  }
       else
       {
      JOptionPane.showMessageDialog(null,"Wait Untill Time Out");     
       }*/
    }//GEN-LAST:event_rbtnActionPerformed
    catch(Exception e){
        
    }
    }
    
    
    public void click()
{
  if(r1.isSelected()){
        right=r1.getText();
        }
        else  if(r2.isSelected()){
        right=r2.getText();
        } 
        else  if(r3.isSelected()){
        right=r3.getText();
        } 
        else  if(r4.isSelected()){
        right=r4.getText();
        } 
        JOptionPane.showMessageDialog(null,right);
        JOptionPane.showMessageDialog(null,ans);
   
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lq;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JButton rbtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
         int minute=Integer.parseInt(dbcount)-1,second=59;
        lbl.setText(""+minute+":"+second);
        while(true)
        {
            try{
                Thread.sleep(1000);
            }
                catch(Exception e)
                        {
                        
                        }
            second--;
            
        if(second==00 && minute==00) 
        {
           // new result().setVisible(true);
         //   JOptionPane.showMessageDialog(null,"stop");
            new result(uname).setVisible(true);
        }
        if(second==00)
        {
        minute--;
        second=59;
        }
        //m.setText();
        lbl.setText(""+minute+":"+second);
        
        }
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
